title: <p align="center"> Vicky Kosambiya</p>
description:   
  <p align="center"> |
  <a style="color:White;" href="https://www.linkedin.com/in/vicky-kosambiya/">LinkedIn</a> |
  <a style="color:White;" href="">GitHub</a> |
  
  <br>
  <br>
  Working as a Software Engineer at Accord Fintech
  <br>
  I have hands-on experience in Python (Numpy, Pandas, Matplotlib, Seaborn)
  MySQL, SQLite, Tableau, R Programming Language (ggplot), Statistics and Probability 
  <br>
  </p>

theme: jekyll-theme-cayman
